### ISSUE TITLE
[建议]将CDN的内容用Base64塞进脚本里面

### ISSUE THREAD

**Issue by arenekosreal** [AntaresQAQ/fuck-daxuexi#1]
dalao可以试试
```css
.base64-url {
  background-image: url("//static.base64.guru/uploads/images/1x3.gif")
}
```
和
```css
.base64-data {
  background-image: url("data:image/gif;base64,R0lGODdhAQADAPABAP////8AACwAAAAAAQADAAACAgxQADs=")
}
```
是等效的
参考：https://base64.guru/developers/data-uri
